In [2]:
import torch
import torch.nn as nn
from model.attention import *
from model.embeddings import *
from model.layer_norm  import *
from model.transformer_mlp import *
from model.transformer_block import *
from model.transformer_model import *

In [3]:
k = torch.rand((2, 3, 4)) # batch x words x d_model
Wk = torch.rand(4, 4) #d_model x d_model
Wq = torch.rand(4, 4) #d_model x d_model
K = (Wk @ k.transpose(-2, -1) ).transpose(-2, -1)
Q = (Wq @ k.transpose(-2, -1) ).transpose(-2, -1)

In [4]:
Q[0], K[0]

(tensor([[0.8758, 1.3845, 1.8956, 1.7097],
         [1.0354, 0.7647, 1.3465, 1.2667],
         [1.1589, 1.7530, 2.5708, 2.3320]]),
 tensor([[0.8823, 1.5489, 1.6262, 1.3652],
         [0.6445, 0.8173, 1.2710, 0.6885],
         [0.7545, 1.4069, 1.8011, 1.5804]]))

In [5]:
(Q@(K.transpose(-2, -1)))[0]

tensor([[ 8.3337,  5.2824,  8.7249],
        [ 6.0169,  3.8759,  6.2843],
        [11.1018,  7.0527, 11.6566]])

In [6]:
Q[0][0]@K[0][1]

tensor(5.2824)

In [8]:
Q.mean(dim=-1, keepdim=True).shape

torch.Size([2, 3, 1])